# Insert your SSID and Your PWD after inital setup
wifi:
  #use_address: 10.7.4.6
  networks:
    - ssid: !secret wifi_ssid          # Uncomment this line (remove # at beginning of line) and enter your details in secrets.yaml file!
      password: !secret wifi_password  # Uncomment this line (remove # at beginning of line) and enter your details in secrets.yaml file!
  ap:
    ssid: ${devicename}
  fast_connect: true

captive_portal:

substitutions:
  devicename: "Radiateur chambre enfants"
  friendly_name: "Radiateur chbr enfants"

esphome:
  name: radiateur_chambre_enfants
  platform: ESP8266
  board: d1_mini
  

# api connection success init led + mode
  on_boot:
    priority: -10
    then:
    - wait_until:
        api.connected:
    - logger.log: API is connected!
    - output.turn_on: led_green
    - switch.turn_off: mode_confort_1_enabled
    - switch.turn_off: mode_confort_1_enabled
    - switch.turn_off: mode_confort_2_enabled
    - switch.turn_off: mode_eco_enabled
    - switch.turn_off: mode_hors_gel_enabled
    - switch.turn_on: arret_enabled

web_server:
  port: 80
  version: 2
  include_internal: true
  auth:
    username: admin
    password: XXXXXX

button:
  - platform: restart
    name: "Restart Device"
    
# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

  
# FilsPilotes States D1 - D2 :
# Arrêt:    LOW  - HIGH 
# Hors Gel: HIGH - LOW  
# Eco :     LOW  - LOW  
# Confort - 2: HIGH - HIGH / LOW - LOW + signal ticker inverter 4m53s / 7s
# Confort - 1: HIGH - HIGH / LOW - LOW + signal ticker inverter 4m57s / 3s
# Confort : HIGH - HIGH 

# Define switches to control position from HA
# Ok, i think we can do this better, but it works for me
switch:
  - platform: template
    name: "${friendly_name} Mode confort"
    id: mode_confort_enabled
    icon: mdi:weather-sunny
    optimistic: true
    on_turn_on:
      then:
        - switch.turn_off: mode_confort_1_enabled
        - switch.turn_off: mode_confort_2_enabled
        - switch.turn_off: mode_eco_enabled
        - switch.turn_off: mode_hors_gel_enabled
        - switch.turn_off: arret_enabled
        - delay: 500 ms
        - output.turn_on: mode_confort
    on_turn_off:
      then:
        - switch.turn_on: arret_enabled
        
  - platform: template
    name: "${friendly_name} Mode confort -1"
    id: mode_confort_1_enabled
    icon: mdi:numeric-1-box-outline
    optimistic: true
    on_turn_on:
      then:
        - switch.turn_off: mode_confort_enabled
        - switch.turn_off: mode_confort_2_enabled
        - switch.turn_off: mode_eco_enabled
        - switch.turn_off: mode_hors_gel_enabled
        - switch.turn_off: arret_enabled
        - delay: 500 ms
        - output.turn_on: mode_confort_1
    on_turn_off:
      then:
        - switch.turn_on: arret_enabled
  - platform: template
    name: "${friendly_name} Mode confort -2"
    id: mode_confort_2_enabled
    icon: mdi:numeric-2-box-outline
    optimistic: true
    on_turn_on:
      then:
        - switch.turn_off: mode_confort_enabled
        - switch.turn_off: mode_confort_1_enabled
        - switch.turn_off: mode_eco_enabled
        - switch.turn_off: mode_hors_gel_enabled
        - switch.turn_off: arret_enabled
        - delay: 500 ms
        - output.turn_on: mode_confort_2
    on_turn_off:
      then:
        - switch.turn_on: arret_enabled
  - platform: template
    name: "${friendly_name} Mode Eco"
    id: mode_eco_enabled
    icon: mdi:cash-usd
    optimistic: true
    on_turn_on:
      then:
        - switch.turn_off: mode_confort_enabled
        - switch.turn_off: mode_confort_1_enabled
        - switch.turn_off: mode_confort_2_enabled
        - switch.turn_off: mode_hors_gel_enabled
        - switch.turn_off: arret_enabled
        - delay: 500 ms
        - output.turn_on: mode_eco
    on_turn_off:
      then:
        - switch.turn_on: arret_enabled
  - platform: template
    name: "${friendly_name} Mode Hors Gel"
    id: mode_hors_gel_enabled
    icon: mdi:weather-snowy
    optimistic: true
    on_turn_on:
      then:
        - switch.turn_off: mode_confort_enabled
        - switch.turn_off: mode_confort_1_enabled
        - switch.turn_off: mode_confort_2_enabled
        - switch.turn_off: mode_eco_enabled
        - switch.turn_off: arret_enabled
        - delay: 500 ms
        - output.turn_on: mode_hors_gel
    on_turn_off:
      then:
        - switch.turn_on: arret_enabled
  - platform: template
    name: "${friendly_name} Arrêt"
    id: arret_enabled
    icon: mdi:stop
    optimistic: true
    on_turn_on:
      then:
        - switch.turn_off: mode_confort_enabled
        - switch.turn_off: mode_confort_1_enabled
        - switch.turn_off: mode_confort_2_enabled
        - switch.turn_off: mode_eco_enabled
        - switch.turn_off: mode_hors_gel_enabled
        - delay: 500 ms
        - output.turn_on: arret

# Enable Home Assistant API
api:

# Enable logging
logger:

ota:
  platform: esphome

# OUTPUTs are :
# GPIO14 - D5 : Green led
# GPIO12 - D6 : Red Led
# GPIO5  - D1 : FPA
# GPIO4  - D2 : FPB

output:
  # Green Led
  - platform: esp8266_pwm
    pin: D5
    id: led_green
  - platform: esp8266_pwm
    pin: D1
    id: fpa
  - platform: esp8266_pwm
    pin: D2
    id: fpb
  - platform: template
    id: mode_confort
    type: binary
    write_action:
      - output.turn_on: fpa
      - output.turn_on: fpb
  # beviahour can be special there.. i don't use it but it was for the sport..
  - platform: template
    id: mode_confort_1
    type: binary
    write_action:
      - while:
          condition:
            switch.is_on: mode_confort_1_enabled
          then:
            - output.turn_off: fpa
            - output.turn_off: fpb
            - delay: 3000 ms
            - output.turn_on: fpa
            - output.turn_on: fpb
            - delay: 297000 ms
  # beviahour can be special there.. i don't use it but it was for the sport..
  - platform: template
    id: mode_confort_2
    type: binary
    write_action:
      - while:
          condition:
            switch.is_on: mode_confort_2_enabled
          then:
            - output.turn_off: fpa
            - output.turn_off: fpb
            - delay: 7000 ms
            - output.turn_on: fpa
            - output.turn_on: fpb
            - delay: 293000 ms
  - platform: template
    id: mode_eco
    type: binary
    write_action:
      - output.turn_off: fpa
      - output.turn_off: fpb
  - platform: template
    id: mode_hors_gel
    type: binary
    write_action:
      - output.turn_on: fpa
      - output.turn_off: fpb
  - platform: template
    id: arret
    type: binary
    write_action:
      - output.turn_off: fpa
      - output.turn_on: fpb

# Red led for booting / flash / errors / issues
status_led: 
    pin: D6
    
sensor:
  # Reports the WiFi signal strength
  - platform: wifi_signal
    name: Signal
    update_interval: 60s
  # Reports how long the device has been powered (in minutes)
  - platform: uptime
    name: Uptime
    filters:
      - lambda: return x / 60.0;
    unit_of_measurement: minutes
  
  # Power usage sensor
  - platform: template
    name: "${friendly_name} Power Usage"
    id: power_usage
    unit_of_measurement: W
    icon: mdi:power
    accuracy_decimals: 0
    lambda: |-
      if (id(mode_confort_enabled).state || id(mode_confort_1_enabled).state || id(mode_confort_2_enabled).state || id(mode_eco_enabled).state) {
        return 1500.0; 
      } else {
        return 0.0;
      }

  # Energy consumption sensor (cumulative kWh)
  - platform: integration
    name: "${friendly_name} Energy Usage"
    sensor: power_usage
    unit_of_measurement: Wh
    icon: mdi:counter
    accuracy_decimals: 3
    time_unit: h



text_sensor:
  - platform: version
    name: ESPHome Version
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    bssid:
      name: Connected BSSID
    mac_address:
      name: Mac Wifi Address
    scan_results:
      name: Latest Scan Results
