# Insert your SSID and Your PWD after initial setup
wifi:
  # Use the following line for setup only when you want to change the device name
  # use_address: 10.7.4.7

  # Define your Wi-Fi network credentials in the secrets.yaml file
  networks:
    - ssid: !secret wifi_ssid          # Uncomment and specify your Wi-Fi SSID in secrets.yaml
      password: !secret wifi_password  # Uncomment and specify your Wi-Fi password in secrets.yaml

  # Access Point (AP) settings
  ap:
    ssid: ${devicename}  # SSID for the AP
  fast_connect: true     # Enable fast connect for Wi-Fi

# Captive Portal for configuration (if needed)
captive_portal:

# Define substitutions for device name and friendly name
substitutions:
  devicename: "Radiateur salon"   # Device name for identification
  friendly_name: "Radiateur salon"  # Friendly name for display

# Main ESPHome configuration
esphome:
  name: radiateur_salon   # Name used for network identification with myDNS
  platform: ESP8266        # Target platform
  board: d1_mini           # Board type (in this case, a Wemos D1 Mini)

# Define actions to run on boot
on_boot:
  priority: -10
  then:
    - wait_until:
        api.connected:   # Wait until the Home Assistant API is connected
    - logger.log: API is connected!  # Log a message indicating API connection
    - output.turn_on: led_green  # Turn on the green LED
    - switch.turn_off: mode_confort_1_enabled
    - switch.turn_off: mode_confort_1_enabled
    - switch.turn_off: mode_confort_2_enabled
    - switch.turn_off: mode_eco_enabled
    - switch.turn_off: mode_hors_gel_enabled
    - switch.turn_on: arret_enabled

# Web server configuration with authentication
web_server:
  port: 80
  version: 2
  include_internal: true
  auth:
    username: admin
    password: xxxxxx

# Sync time with Home Assistant.
time:
  - platform: sntp
    id: homeassistant_time
  
# Define switches to control different heating modes
switch:
  - platform: template
    name: "${friendly_name} Mode confort"   # Comfort mode
    id: mode_confort_enabled
    icon: mdi:weather-sunny
    optimistic: true
    on_turn_on:
      then:
        - switch.turn_off: mode_confort_1_enabled
        - switch.turn_off: mode_confort_2_enabled
        - switch.turn_off: mode_eco_enabled
        - switch.turn_off: mode_hors_gel_enabled
        - switch.turn_off: arret_enabled
        - delay: 500 ms
        - output.turn_on: mode_confort
    on_turn_off:
      then:
        - switch.turn_on: arret_enabled

  - platform: template
    name: "${friendly_name} Mode confort -1"  # Comfort -1 mode
    id: mode_confort_1_enabled
    icon: mdi:numeric-1-box-outline
    optimistic: true
    on_turn_on:
      then:
        - switch.turn_off: mode_confort_enabled
        - switch.turn_off: mode_confort_2_enabled
        - switch.turn_off: mode_eco_enabled
        - switch.turn_off: mode_hors_gel_enabled
        - switch.turn_off: arret_enabled
        - delay: 500 ms
        - output.turn_on: mode_confort_1
    on_turn_off:
      then:
        - switch.turn_on: arret_enabled

  - platform: template
    name: "${friendly_name} Mode confort -2"  # Comfort -2 mode
    id: mode_confort_2_enabled
    icon: mdi:numeric-2-box-outline
    optimistic: true
    on_turn_on:
      then:
        - switch.turn_off: mode_confort_enabled
        - switch.turn_off: mode_confort_1_enabled
        - switch.turn_off: mode_eco_enabled
        - switch.turn_off: mode_hors_gel_enabled
        - switch.turn_off: arret_enabled
        - delay: 500 ms
        - output.turn_on: mode_confort_2
    on_turn_off:
      then:
        - switch.turn_on: arret_enabled

  - platform: template
    name: "${friendly_name} Mode Eco"   # Eco mode
    id: mode_eco_enabled
    icon: mdi:cash-usd
    optimistic: true
    on_turn_on:
      then:
        - switch.turn_off: mode_confort_enabled
        - switch.turn_off: mode_confort_1_enabled
        - switch.turn_off: mode_confort_2_enabled
        - switch.turn_off: mode_hors_gel_enabled
        - switch.turn_off: arret_enabled
        - delay: 500 ms
        - output.turn_on: mode_eco
    on_turn_off:
      then:
        - switch.turn_on: arret_enabled

  - platform: template
    name: "${friendly_name} Mode Hors Gel"   # Frost protection mode
    id: mode_hors_gel_enabled
    icon: mdi:weather-snowy
    optimistic: true
    on_turn_on:
      then:
        - switch.turn_off: mode_confort_enabled
        - switch.turn_off: mode_confort_1_enabled
        - switch.turn_off: mode_confort_2_enabled
        - switch.turn_off: mode_eco_enabled
        - switch.turn_off: arret_enabled
        - delay: 500 ms
        - output.turn_on: mode_hors_gel
    on_turn_off:
      then:
        - switch.turn_on: arret_enabled

  - platform: template
    name: "${friendly_name} Arrêt"   # Stop mode
    id: arret_enabled
    icon: mdi:stop
    optimistic: true
    on_turn_on:
      then:
        - switch.turn_off: mode_confort_enabled
        - switch.turn_off: mode_confort_1_enabled
        - switch.turn_off: mode_confort_2_enabled
        - switch.turn_off: mode_eco_enabled
        - switch.turn_off: mode_hors_gel_enabled
        - delay: 500 ms
        - output.turn_on: arret

# Enable Home Assistant API
api:

# Enable logging
logger:

# OTA (Over-the-Air) updates
ota:

# Define output pins for LEDs and heating modes
output:
  # Green Led
  - platform: esp8266_pwm
    pin: D5
    id: led_green
  - platform: esp8266_pwm
    pin: D1
    id: fpa
  - platform: esp8266_pwm
    pin: D2
    id: fpb

# Define heating modes as binary switches
  - platform: template
    id: mode_confort
    type: binary
    write_action:
      - output.turn_on: fpa
      - output.turn_on: fpb

  - platform: template
    id: mode_confort_1
    type: binary
    write_action:
      - while:
          condition:
            switch.is_on: mode_confort_1_enabled
          then:
            - output.turn_off: fpa
            - output.turn_off: fpb
            - delay: 3000 ms
            - output.turn_on: fpa
            - output.turn_on: fpb
            - delay: 297000 ms

  - platform: template
    id: mode_confort_2
    type: binary
    write_action:
      - while:
          condition:
            switch.is_on: mode_confort_2_enabled
          then:
            - output.turn_off: fpa
            - output.turn_off: fpb
            - delay: 7000 ms
            - output.turn_on: fpa
            - output.turn_on: fpb
            - delay: 293000 ms

  - platform: template
    id: mode_eco
    type: binary
    write_action:
      - output.turn_off: fpa
      - output.turn_off: fpb

  - platform: template
    id: mode_hors_gel
    type: binary
    write_action:
      - output.turn_on: fpa
      - output.turn_off: fpb

  - platform: template
    id: arret
    type: binary
    write_action:
      - output.turn_off: fpa
      - output.turn_on: fpb

# Red led for booting / flash / errors / issues
status_led: 
    pin: D6
    
# Sensor configuration
sensor:
  # Reports the WiFi signal strength
  - platform: wifi_signal
    name: Signal
    update_interval: 60s
  # Reports how long the device has been powered (in minutes)
  - platform: uptime
    name: Uptime
    filters:
      - lambda: return x / 60.0;
    unit_of_measurement: minutes

text_sensor:
  - platform: version
    name: ESPHome Version
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    bssid:
      name: Connected BSSID
    mac_address:
      name: Mac Wifi Address
    scan_results:
      name: Latest Scan Results

button:
  - platform: restart
    name: "Restart Device"
